import type { NextPage } from "next";
import Header from "../../../components/Header";
import AdvancedEmissionsTrackingSecti from "../../../components/AdvancedEmissionsTrackingSecti";
import ComprehensiveProjectManagement from "../../../components/ComprehensiveProjectManagement";
import TrainingAndSupportContainer from "../../../components/TrainingAndSupportContainer";
import FormContainer2 from "../../../components/FormContainer2";
import styles from "./ResourcesIndustryConstruc.module.css";
import Footer from "../../../components/Footer";
import ContactFormContainer from "../../../components/ContactFormContainer";
import CardContainer from "../../../components/CardContainer";

const ResourcesIndustryConstruc: NextPage = () => {
  const accordionData = [
    {
      header: "What sustainability certifications can Luxa help us achieve?",
      description: "Luxa is designed to assist with a range of sustainability certifications, including LEED, BREEAM, and WELL Building Standards. Our platform streamlines the compliance process by managing documentation, tracking sustainability metrics, and providing actionable insights to meet certification criteria effectively."
    },
    {
      header: "How does Luxa's emissions tracking feature benefit our construction projects?",
      description: "Luxa’s emissions tracking feature offers real-time monitoring and reporting of carbon emissions from your construction activities. This enables you to make informed decisions to reduce your environmental impact, meet regulatory requirements, and demonstrate your commitment to sustainability to stakeholders and clients."
    },
    {
      header: "Can Luxa integrate with our existing project management tools?",
      description: "Absolutely. Luxa is designed for seamless integration with a variety of existing project management tools. Our goal is to enhance your current systems with advanced sustainability tracking and reporting capabilities, not replace them."
    },
    {
      header: "Is Luxa suitable for small-scale construction projects or only large ones?",
      description: "Luxa is scalable and versatile, making it suitable for construction projects of all sizes. Whether it’s a small residential project or a large commercial development, Luxa can be tailored to meet your specific sustainability tracking and reporting needs."
    },
    {
      header: "How user-friendly is Luxa for teams not familiar with sustainability practices?",
      description: "Luxa is designed with user-friendliness in mind. It offers an intuitive interface and straightforward tools that make sustainability management accessible, even for teams that are new to these practices. Additionally, we provide comprehensive support and training materials to help all users get the most out of our platform."
    },
    {
      header: "Does Luxa offer any support or guidance for sustainability compliance?",
      description: "Yes, Luxa offers extensive support and guidance for sustainability compliance. Our platform includes resources and tools that help you understand and adhere to relevant sustainability standards and regulations. Furthermore, our dedicated support team is always available to provide personalized assistance and advice on best practices in sustainability compliance."
    },
    {
      header: "How does Luxa ensure the accuracy of its sustainability data and reports?",
      description: "Luxa employs advanced data verification methods and uses reliable sources for data collection to ensure accuracy. Our platform utilizes a combination of real-time data feeds, manual entry verification processes, and checks against established benchmarks and standards. This multi-layered approach ensures that the sustainability data and reports generated by Luxa are both accurate and trustworthy, making them suitable for compliance documentation and stakeholder communication."
    }
  ];
  return (
 
    <div className={styles.resourcesIndustryConstruc}>
      {/* <div className={styles.resourcesIndustryConstrucChild} /> */}
      <Header
        projectDescription="Revolutionizing the Construction Industry with Luxa"
        constructionManagementDes="At the forefront of innovation, Luxa is redefining construction project management by integrating cutting-edge sustainability solutions. Our platform uniquely combines real-time emissions tracking, streamlined certification processes, and data-driven insights, setting a new standard in eco-conscious construction practices."
        readyToLearnFrameGap="152px"
        propPadding="0px 0px var(--padding-8xl)" activeLink={""}      />
      <AdvancedEmissionsTrackingSecti />
      <section className={styles.lEEDServices}>
        <ComprehensiveProjectManagement />
      </section>
      <TrainingAndSupportContainer />
      <FormContainer2 />
      <section className={styles.faqsOnLeedCertificationManParent}>
        <h1 className={styles.faqsOnLeed}>
          FAQs
        </h1>
        <CardContainer accordionData={accordionData}/>
      </section>
      <ContactFormContainer
        imageSize="/frame1.svg"
        contactMessage="Schedule a Demo or Consultation"
        renovationImageUrl="/frame-11@2x.png"
        propPadding="109px var(--padding-60xl)"
        propMinHeight="458px"
        propBottom="-74px"
      />
        <Footer/>
    </div>
  );
};

export default ResourcesIndustryConstruc;
